# Generated by Django 5.2.9 on 2025-12-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_usersession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="otp",
            table="user_otps",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="usersession",
            table="user_sessions",
        ),
    ]
