"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv


# Load environment variables
# Load environment variables
load_dotenv()

# Filter upstream warnings from dj-rest-auth (incompatibility with latest allauth)
import warnings
warnings.filterwarnings('ignore', message='.*app_settings.USERNAME_REQUIRED is deprecated.*')
warnings.filterwarnings('ignore', message='.*app_settings.EMAIL_REQUIRED is deprecated.*')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ... (skipping to Authentication Backends)
# -----------------------------------------------------------------------------
# AUTHENTICATION CONFIGURATION
# -----------------------------------------------------------------------------

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Optional OTP authentication backend: only include if provided by installed
# django-otp package to avoid import-time errors on newer versions which
# don't expose a `django_otp.backends` module.
# Optional OTP authentication backend
# If you want to require OTP for admin login, you might need this, 
# but simply having the middleware is often enough for custom views.
# We will leave the standard ModelBackend.


# RAZORPAY SETTINGS
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-4*2*ie!i8y=bb=gxpc=-knf^*yitz74@wym$)w^w30n_q9+hki')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    "ninja-pdf.onrender.com",
    "localhost",
    "127.0.0.1",
    "https://octopus-app-4mzsp.ondigitalocean.app",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'core', # Added for SystemSetting/AdminRequest models
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic', # WhiteNoise dev support
    'django.contrib.sites',  # Required by allauth

    # Third Party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',


    # Domain Apps (Consolidated)
    'apps.accounts',
    'apps.subscriptions',
    'apps.files',
    'apps.jobs',
    'apps.tools',
    'apps.teams',
    'apps.workflows',
    'apps.signatures',
]


SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise Middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware', # AllAuth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'emails/templates',
            BASE_DIR / 'static', 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', '18plus'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'ninja'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 600, # Persistent connections (10 mins) for optimization
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------------------------------------------
# EMAIL CONFIGURATION (Zepto Mail - Production Ready)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# EMAIL CONFIGURATION (Zepto Mail - API)
# -----------------------------------------------------------------------------
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@18pluspdf.com')
# Use Custom Zepto API Backend
EMAIL_BACKEND = 'core.email_backend.ZeptoEmailBackend'

# Zepto Mail Configuration
ZEPTO_API_URL = "https://api.zeptomail.in/v1.1/email"
ZEPTO_API_KEY = os.getenv('ZEPTO_API_KEY')


# -----------------------------------------------------------------------------
# AUTHENTICATION CONFIGURATION
# -----------------------------------------------------------------------------

AUTH_USER_MODEL = 'accounts.User'

# REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    # Throttling to protect auth endpoints and brute-force attempts
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'anon': '20/min',
        'user': '100/min',  # Standard authenticated user limit
        'password_reset': '5/hour',
        'registration': '5/hour',
        'otp': '10/min',
        'dj_rest_auth': '100/min',
    }
}

# JWT Configuration
SIMPLE_JWT = {
    # Shorter lifetimes for government-grade security
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# dj-rest-auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'JWT_AUTH_HTTPONLY': True,  # Prevent JS access
    # Recommend SameSite=Strict in production for CSRF protection on cookies
    'JWT_AUTH_SAMESITE': os.getenv('JWT_AUTH_SAMESITE', 'Lax'),
    # For local development don't hardcode a cookie domain so it's host-specific.
    # This avoids issues when frontend runs on `localhost` while backend is `127.0.0.1`.
    'JWT_AUTH_COOKIE_DOMAIN': None,
    'SESSION_LOGIN': False,
    'LOGIN_SERIALIZER': 'apps.accounts.api.serializers.CustomLoginSerializer',
    'USER_DETAILS_SERIALIZER': 'apps.accounts.api.serializers.UserSerializer',
}

# Cookie config used by helpers
JWT_COOKIE_SAMESITE = REST_AUTH.get('JWT_AUTH_SAMESITE', 'Strict')

# AllAuth Configuration
# AllAuth Configuration (2025 Modern Standards)
# AllAuth Configuration (2025 Modern Standards)
# AllAuth Configuration (Modern Standard)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*'] # Standard flow with confirmation
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# CSRF Settings for JWT Auth
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Critical: Frontend needs to read this cookie
CSRF_USE_SESSIONS = False 

# Validation is handled by RegisterSerializer and settings above.
ACCOUNT_CONFIRM_EMAIL_ON_GET = False # Secure: Requires POST to verify
ACCOUNT_ADAPTER = 'apps.accounts.services.adapters.CustomAccountAdapter'
OLD_PASSWORD_FIELD_ENABLED = True
LOGOUT_ON_PASSWORD_CHANGE = True

# Google Provider
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Avoid showing the intermediate provider confirmation/login page
# (e.g. the 'Continue' button) and instead immediately redirect
# to the provider when initiating OAuth flows. This makes the
# frontend start-to-provider flow immediate.
SOCIALACCOUNT_LOGIN_ON_GET = True

# Explicitly opt-in to automatic signup from social providers so
# users aren't shown a separate signup form after returning from
# the provider unless additional data is required by the adapter.
SOCIALACCOUNT_AUTO_SIGNUP = True

# CORS - Both localhost (development) and deployed URL (production)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend dev URL
    "http://127.0.0.1:3000",
    # Production URLs (add your deployed frontend URL here)
    "https://ninja-pdf.onrender.com",
    "https://octopus-app-4mzsp.ondigitalocean.app",
    "https://ninjapdf.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://18pluspdf.com",
    "https://www.18pluspdf.com",
]
CORS_ALLOW_CREDENTIALS = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "18pluspdf.com", "api.18pluspdf.com", ".onrender.com", ".ondigitalocean.app"]

# CSRF trusted origins for local dev (frontend running on port 3000)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://18pluspdf.com",
    "https://www.18pluspdf.com",
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# -----------------------------------------------------------------------------
# ASYNC & CACHE CONFIGURATION (REDIS)
# -----------------------------------------------------------------------------
# Use Redis for Caching
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_placeholder')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_placeholder')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_placeholder')

from kombu import Queue
CELERY_TASK_QUEUES = (
    Queue('high_priority', routing_key='high_priority'),
    Queue('default', routing_key='default'),
)
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# -----------------------------------------------------------------------------
# CLOUD STORAGE (DYNAMIC: S3 / CLOUDFLARE R2 / LOCAL)
# ENV: STORAGE_BACKEND = 's3' | 'r2' | 'local' (default)
# -----------------------------------------------------------------------------
STORAGE_BACKEND = os.getenv('STORAGE_BACKEND', 'local').lower()

if STORAGE_BACKEND in ('s3', 'r2'):
    # General S3 Compatible Settings (Works for AWS S3, DO Spaces, Cloudflare R2, MinIO)
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    
    # Critical for DigitalOcean Spaces / Compatibility
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL') 
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')

    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = None # Use bucket default (private). Do NOT force public-read on private buckets.
    AWS_QUERYSTRING_AUTH = True # Generate signed URLs
    AWS_S3_ADDRESSING_STYLE = "path" # Fix for Supabase/MinIO path-style URLs
    AWS_S3_SIGNATURE_VERSION = 's3v4' # Enforce v4 signature (required by modern S3/Supabase)
    if STORAGE_BACKEND == 'r2':
        AWS_S3_REGION_NAME = 'auto' # R2 specific
        
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')  # Optional public CDN domain
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Default: FileSystemStorage for local development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

