# Generated by Django 5.2.9 on 2025-12-15 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('VALIDATED', 'Validated'), ('TEMP_STORED', 'Temporarily Stored'), ('METADATA_REGISTERED', 'Metadata Registered'), ('QUEUED', 'Queued for Processing'), ('PROCESSING', 'Processing'), ('OUTPUT_GENERATED', 'Output Generated'), ('PREVIEW_GENERATED', 'Preview Generated'), ('STORED_FINAL', 'Stored Final'), ('AVAILABLE', 'Available'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=25)),
                ('version', models.PositiveIntegerField(default=1)),
                ('md5_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for guest uploads', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Asset',
                'verbose_name_plural': 'File Assets',
                'db_table': 'files_fileasset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_type', models.CharField(default='SYSTEM', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='files.fileasset')),
            ],
            options={
                'db_table': 'files_filestatelog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField()),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.fileasset')),
            ],
            options={
                'db_table': 'files_fileversion',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['user', 'status'], name='files_filea_user_id_3fd6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['user', '-created_at'], name='files_filea_user_id_ec9104_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('file_asset', 'version_number')},
        ),
    ]
