# Generated by Django 5.2.9 on 2025-12-15 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/%Y/%m/%d/')),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('VALIDATED', 'Validated'), ('TEMP_STORED', 'Temp Stored'), ('METADATA_REGISTERED', 'Metadata Registered'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('OUTPUT_GENERATED', 'Output Generated'), ('PREVIEW_GENERATED', 'Preview Generated'), ('STORED_FINAL', 'Stored Final'), ('AVAILABLE', 'Available'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Page count, encryption, tool params')),
                ('expires_at', models.DateTimeField(blank=True, help_text='For temp/guest files', null=True)),
                ('md5_hash', models.CharField(blank=True, help_text='Integrity check', max_length=32, null=True)),
                ('sha256_hash', models.CharField(blank=True, help_text='SHA256 integrity hash', max_length=64, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Sharable via link')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password_hash', models.CharField(blank=True, help_text='Hashed password for access protection', max_length=128, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Asset',
                'verbose_name_plural': 'File Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
