# Generated by Django 5.2.9 on 2025-12-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_cloudprovider_cloudconnection_cloudsyncjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cloudconnection',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='cloudconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cloudsyncjob',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='cloudsyncjob',
            name='local_file',
        ),
        migrations.DeleteModel(
            name='CloudProvider',
        ),
        migrations.DeleteModel(
            name='CloudConnection',
        ),
        migrations.DeleteModel(
            name='CloudSyncJob',
        ),
    ]
