# Generated by Django 5.2.9 on 2025-12-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_cloudconnection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='is_scanned',
            field=models.BooleanField(default=False, help_text='Whether file has been scanned for viruses'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='scan_message',
            field=models.TextField(blank=True, help_text='Details from virus scan'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='scan_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan Error'), ('SKIPPED', 'Skipped')], default='', help_text='Result of virus scan', max_length=50),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
