# Generated by Django 5.2.9 on 2025-12-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_phase1_rbac_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('GOOGLE_DRIVE', 'Google Drive'), ('DROPBOX', 'Dropbox'), ('ONEDRIVE', 'OneDrive'), ('AWS_S3', 'AWS S3'), ('CUSTOM', 'Custom')], max_length=20, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('redirect_uri', models.URLField(blank=True)),
                ('auth_url', models.URLField(blank=True)),
                ('token_url', models.URLField(blank=True)),
                ('api_base_url', models.URLField(blank=True)),
                ('scopes', models.JSONField(default=list, help_text='OAuth scopes required')),
                ('max_file_size_mb', models.PositiveIntegerField(default=100)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cloud_providers/')),
            ],
            options={
                'db_table': 'cloud_providers',
            },
        ),
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('default_folder_id', models.CharField(blank=True, max_length=255)),
                ('default_folder_path', models.CharField(blank=True, max_length=500)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('sync_direction', models.CharField(choices=[('UPLOAD', 'Upload Only'), ('DOWNLOAD', 'Download Only'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Token Expired'), ('REVOKED', 'Revoked'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.cloudprovider')),
            ],
            options={
                'db_table': 'cloud_connections',
                'unique_together': {('user', 'provider', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='CloudSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('remote_file_id', models.CharField(blank=True, max_length=255)),
                ('remote_path', models.CharField(blank=True, max_length=500)),
                ('remote_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='files.cloudconnection')),
                ('local_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.fileasset')),
            ],
            options={
                'db_table': 'cloud_sync_jobs',
            },
        ),
    ]
