# Generated by Django 5.2.9 on 2025-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
