# Generated by Django 5.2.9 on 2025-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_feature_userfeatureoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.ImageField(blank=True, help_text='Feature icon/logo for frontend', null=True, upload_to='features/'),
        ),
    ]
