# Generated by Django 5.2.9 on 2025-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_feature_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='free_limit',
            field=models.IntegerField(default=0, help_text='Number of free uses allowed per day/month (0 = unlimited or strictly premium if is_premium_default is True)'),
        ),
    ]
