export const timezones = [
    { value: "Dateline Standard Time", label: "(GMT-12:00) International Date Line West" },
    { value: "UTC-11", label: "(GMT-11:00) Midway Island, Samoa" },
    { value: "Hawaiian Standard Time", label: "(GMT-10:00) Hawaii" },
    { value: "Alaskan Standard Time", label: "(GMT-09:00) Alaska" },
    { value: "Pacific Standard Time", label: "(GMT-08:00) Pacific Time (US & Canada)" },
    { value: "Mountain Standard Time", label: "(GMT-07:00) Mountain Time (US & Canada)" },
    { value: "Mexico Standard Time 2", label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan" },
    { value: "US Mountain Standard Time", label: "(GMT-07:00) Arizona" },
    { value: "Central Standard Time", label: "(GMT-06:00) Central Time (US & Canada)" },
    { value: "Canada Central Standard Time", label: "(GMT-06:00) Saskatchewan" },
    { value: "Mexico Standard Time", label: "(GMT-06:00) Guadalajara, Mexico City, Monterrey" },
    { value: "Central America Standard Time", label: "(GMT-06:00) Central America" },
    { value: "Eastern Standard Time", label: "(GMT-05:00) Eastern Time (US & Canada)" },
    { value: "US Eastern Standard Time", label: "(GMT-05:00) Indiana (East)" },
    { value: "S.A. Pacific Standard Time", label: "(GMT-05:00) Bogota, Lima, Quito" },
    { value: "Atlantic Standard Time", label: "(GMT-04:00) Atlantic Time (Canada)" },
    { value: "S.A. Western Standard Time", label: "(GMT-04:00) Caracas, La Paz" },
    { value: "Pacific S.A. Standard Time", label: "(GMT-04:00) Santiago" },
    { value: "Newfoundland Standard Time", label: "(GMT-03:30) Newfoundland" },
    { value: "E. South America Standard Time", label: "(GMT-03:00) Brasilia" },
    { value: "S.A. Eastern Standard Time", label: "(GMT-03:00) Buenos Aires, Georgetown" },
    { value: "Greenland Standard Time", label: "(GMT-03:00) Greenland" },
    { value: "Mid-Atlantic Standard Time", label: "(GMT-02:00) Mid-Atlantic" },
    { value: "Azores Standard Time", label: "(GMT-01:00) Azores" },
    { value: "Cape Verde Standard Time", label: "(GMT-01:00) Cape Verde Is." },
    { value: "GMT Standard Time", label: "(GMT+00:00) Dublin, Edinburgh, Lisbon, London" },
    { value: "Greenwich Standard Time", label: "(GMT+00:00) Monrovia, Reykjavik" },
    { value: "UTC", label: "(GMT+00:00) UTC" },
    { value: "Central European Standard Time", label: "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
    { value: "Romance Standard Time", label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" },
    { value: "W. Europe Standard Time", label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
    { value: "W. Central Africa Standard Time", label: "(GMT+01:00) West Central Africa" },
    { value: "E. Europe Standard Time", label: "(GMT+02:00) Bucharest" },
    { value: "Egypt Standard Time", label: "(GMT+02:00) Cairo" },
    { value: "FLE Standard Time", label: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
    { value: "GTB Standard Time", label: "(GMT+02:00) Athens, Istanbul, Minsk" },
    { value: "Israel Standard Time", label: "(GMT+02:00) Jerusalem" },
    { value: "South Africa Standard Time", label: "(GMT+02:00) Harare, Pretoria" },
    { value: "Russian Standard Time", label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd" },
    { value: "Arab Standard Time", label: "(GMT+03:00) Kuwait, Riyadh" },
    { value: "E. Africa Standard Time", label: "(GMT+03:00) Nairobi" },
    { value: "Arabic Standard Time", label: "(GMT+03:00) Baghdad" },
    { value: "Iran Standard Time", label: "(GMT+03:30) Tehran" },
    { value: "Arabian Standard Time", label: "(GMT+04:00) Abu Dhabi, Muscat" },
    { value: "Caucasus Standard Time", label: "(GMT+04:00) Baku, Tbilisi, Yerevan" },
    { value: "Transitional Islamic State of Afghanistan Standard Time", label: "(GMT+04:30) Kabul" },
    { value: "Ekaterinburg Standard Time", label: "(GMT+05:00) Ekaterinburg" },
    { value: "West Asia Standard Time", label: "(GMT+05:00) Islamabad, Karachi, Tashkent" },
    { value: "India Standard Time", label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
    { value: "Nepal Standard Time", label: "(GMT+05:45) Kathmandu" },
    { value: "Central Asia Standard Time", label: "(GMT+06:00) Astana, Dhaka" },
    { value: "Sri Lanka Standard Time", label: "(GMT+06:00) Sri Jayawardenepura" },
    { value: "N. Central Asia Standard Time", label: "(GMT+06:00) Almaty, Novosibirsk" },
    { value: "Myanmar Standard Time", label: "(GMT+06:30) Yangon (Rangoon)" },
    { value: "SE Asia Standard Time", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
    { value: "North Asia Standard Time", label: "(GMT+07:00) Krasnoyarsk" },
    { value: "China Standard Time", label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
    { value: "Singapore Standard Time", label: "(GMT+08:00) Kuala Lumpur, Singapore" },
    { value: "Taipei Standard Time", label: "(GMT+08:00) Taipei" },
    { value: "W. Australia Standard Time", label: "(GMT+08:00) Perth" },
    { value: "North Asia East Standard Time", label: "(GMT+08:00) Irkutsk, Ulaan Bataar" },
    { value: "Korea Standard Time", label: "(GMT+09:00) Seoul" },
    { value: "Tokyo Standard Time", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
    { value: "Yakutsk Standard Time", label: "(GMT+09:00) Yakutsk" },
    { value: "A.U.S. Central Standard Time", label: "(GMT+09:30) Darwin" },
    { value: "Cen. Australia Standard Time", label: "(GMT+09:30) Adelaide" },
    { value: "A.U.S. Eastern Standard Time", label: "(GMT+10:00) Canberra, Melbourne, Sydney" },
    { value: "E. Australia Standard Time", label: "(GMT+10:00) Brisbane" },
    { value: "Tasmania Standard Time", label: "(GMT+10:00) Hobart" },
    { value: "Vladivostok Standard Time", label: "(GMT+10:00) Vladivostok" },
    { value: "West Pacific Standard Time", label: "(GMT+10:00) Guam, Port Moresby" },
    { value: "Central Pacific Standard Time", label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia" },
    { value: "Fiji Standard Time", label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is." },
    { value: "New Zealand Standard Time", label: "(GMT+12:00) Auckland, Wellington" },
    { value: "Tonga Standard Time", label: "(GMT+13:00) Nuku'alofa" }
];
