# Generated by Django 5.2.9 on 2025-12-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_remove_plan_apply_watermark_and_more'),
        ('teams', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_organization',
            field=models.BooleanField(default=False, help_text='Enterprise organization account'),
        ),
        migrations.AddField(
            model_name='team',
            name='operations_quota',
            field=models.PositiveIntegerField(default=0, help_text='Monthly operations quota (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='team',
            name='shared_plan',
            field=models.ForeignKey(blank=True, help_text='Shared subscription plan for all team members', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='team',
            name='storage_quota',
            field=models.BigIntegerField(default=0, help_text='Storage quota in bytes (0 = unlimited)'),
        ),
    ]
