# Generated by Django 5.2.9 on 2025-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('TRASH', 'Trash')], default='DRAFT', max_length=20),
        ),
    ]
