# Generated by Django 5.2.9 on 2025-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='storage_limit',
            field=models.BigIntegerField(default=104857600, help_text='Storage limit in bytes (Default 100MB)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='storage_used',
            field=models.BigIntegerField(default=0, help_text='Current storage usage in bytes'),
        ),
    ]
