# Generated by Django 5.2.9 on 2025-12-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_premiumrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Config key (e.g. 'GLOBAL_MAX_FILE_SIZE')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Config value')),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Expose to frontend via public API?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('limit', models.IntegerField(default=-1, help_text='Usage limit per interval (-1 for unlimited)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional config (e.g. max request size for this feature)')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.plan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
