# Generated by Django 5.2.9 on 2025-12-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_systemsetting_planfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[('TOOL', 'Tool'), ('PERMISSION', 'Permission'), ('SYSTEM_CONFIG', 'System Config')], default='TOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='permission_id',
            field=models.PositiveIntegerField(blank=True, help_text='Role-Based Task ID (1-203)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.SlugField(help_text="Unique code used in code checks (e.g. 'MERGE_PDF')", unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='free_limit',
            field=models.IntegerField(default=0, help_text='Number of free uses allowed per day/month'),
        ),
    ]
