# Generated by Django 5.2.9 on 2025-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global System Toggle for this feature'),
        ),
        migrations.AddField(
            model_name='userfeatureoverride',
            name='limit',
            field=models.IntegerField(blank=True, default=-1, help_text='Usage limit override (-1 for unlimited, null to use plan limit)', null=True),
        ),
    ]
