# Generated by Django 5.2.9 on 2025-12-16 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_feature_is_active_userfeatureoverride_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('GST', 'GST'), ('SALES_TAX', 'Sales Tax'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as percentage', max_digits=5)),
                ('tax_id_required', models.BooleanField(default=False, help_text='Is tax ID required for B2B?')),
                ('reverse_charge_applicable', models.BooleanField(default=False)),
                ('stripe_tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tax_configurations',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Internal name for reference', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for indefinite', null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='0 = unlimited per user')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_users_only', models.BooleanField(default=False)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('EXHAUSTED', 'Exhausted'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Leave empty for all plans', to='subscriptions.plan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_usages',
            },
        ),
        migrations.CreateModel(
            name='TrialConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveIntegerField(default=7)),
                ('is_enabled', models.BooleanField(default=True)),
                ('requires_payment_method', models.BooleanField(default=False)),
                ('allow_multiple_trials', models.BooleanField(default=False, help_text='Allow same user multiple trials')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_config', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'trial_configurations',
            },
        ),
        migrations.CreateModel(
            name='RegionalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_prices', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'regional_pricing',
                'unique_together': {('plan', 'country_code')},
            },
        ),
    ]
