# Generated by Django 5.2.9 on 2025-12-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_taxconfiguration_coupon_couponusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='apply_watermark',
            field=models.BooleanField(default=True, help_text='Apply watermark to processed PDFs'),
        ),
        migrations.AddField(
            model_name='plan',
            name='concurrent_job_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max simultaneous processing jobs'),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_operations_limit',
            field=models.PositiveIntegerField(default=10, help_text='Daily operations limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_file_size',
            field=models.BigIntegerField(default=10485760, help_text='Max upload file size in bytes (Default 10MB)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_output_quality',
            field=models.CharField(default='STANDARD', help_text='Maximum output quality (DRAFT/STANDARD/HIGH/PRINT)', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_pages_per_operation',
            field=models.PositiveIntegerField(default=50, help_text='Max pages per single operation'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_operations_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly operations limit (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_pages_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly pages processed limit (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='processing_priority',
            field=models.CharField(choices=[('LOW', 'Low (Free tier)'), ('NORMAL', 'Normal'), ('HIGH', 'High (Priority)'), ('REALTIME', 'Realtime (Enterprise)')], default='LOW', help_text='Queue priority for PDF processing jobs', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='show_ads',
            field=models.BooleanField(default=True, help_text='Show advertisements to users on this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='watermark_text',
            field=models.CharField(blank=True, default='Created with Ninja PDF', help_text='Watermark text for free tier', max_length=100),
        ),
    ]
