# Generated by Django 5.2.9 on 2025-12-16 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_plan_apply_watermark_plan_concurrent_job_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('FREE_TO_PREMIUM', 'Move to Premium Only'), ('PREMIUM_TO_FREE', 'Make Available to Free'), ('ENABLE_TOOL', 'Enable Tool Globally'), ('DISABLE_TOOL', 'Disable Tool Globally'), ('ADJUST_LIMIT', 'Adjust Usage Limits'), ('TOGGLE_WATERMARK', 'Toggle Watermark')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for the change')),
                ('new_value', models.JSONField(blank=True, help_text='New value for limits/config', null=True)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value (auto-captured)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='subscriptions.feature')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tool_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Change Request',
                'verbose_name_plural': 'Tool Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
