# Generated by Django 5.2.9 on 2025-12-16 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_tool_change_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='apply_watermark',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='concurrent_job_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='daily_operations_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_file_size',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_output_quality',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_pages_per_operation',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_operations_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_pages_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='processing_priority',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='show_ads',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='watermark_text',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='config',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='premiumrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='value_type',
        ),
        migrations.RemoveField(
            model_name='userfeatureoverride',
            name='limit',
        ),
        migrations.AddField(
            model_name='planfeature',
            name='daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='monthly_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_premium_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[('TOOL', 'PDF Tool'), ('PERMISSION', 'Permission'), ('SYSTEM_CONFIG', 'System Configuration')], default='PERMISSION', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.SlugField(help_text='Unique code used in code checks', unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='free_limit',
            field=models.IntegerField(default=0, help_text='Number of free uses allowed per day/month (0 = unlimited or strictly premium if is_premium_default is True)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global toggle to enable/disable this feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='permission_id',
            field=models.PositiveIntegerField(blank=True, help_text='Maps to RBAC specification task ID (1-203)', null=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='subscriptions.feature'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='premium_proofs/'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='subscriptions.feature'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(help_text='USER, ADMIN, or SUPER_ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this setting is visible to non-admin users'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(),
        ),
    ]
