# Generated by Django 5.2.9 on 2025-12-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_remove_plan_apply_watermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether subscription is in trial period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_converted',
            field=models.BooleanField(default=False, help_text='Whether trial was converted to paid'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When trial ends', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When trial started', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('TRIAL', 'Trial'), ('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('GRACE_PERIOD', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled'), ('PAST_DUE', 'Past Due')], default='FREE', max_length=20),
        ),
    ]
