# Generated by Django 5.2.9 on 2025-12-17 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_add_trial_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(default='NinjaPDF', max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('company_tax_id', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='billing/')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('supported_currencies', models.JSONField(default=list, help_text='List of supported currency codes')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_start_number', models.PositiveIntegerField(default=1000)),
                ('invoice_footer', models.TextField(blank=True, help_text='Footer text for invoices')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, help_text='Days until payment is due (0 = immediate)')),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Grace period after failed payment')),
                ('retry_failed_payments', models.BooleanField(default=True)),
                ('max_payment_retries', models.PositiveIntegerField(default=3)),
                ('collect_tax', models.BooleanField(default=True)),
                ('tax_inclusive_pricing', models.BooleanField(default=False)),
                ('require_tax_id_for_business', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_configuration',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique identifier for the feature flag (e.g., 'new_pdf_editor')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this flag controls')),
                ('category', models.CharField(choices=[('UI', 'User Interface'), ('FEATURE', 'Feature'), ('EXPERIMENT', 'Experiment'), ('OPERATION', 'Operations'), ('BETA', 'Beta')], default='FEATURE', max_length=20)),
                ('rollout_type', models.CharField(choices=[('GLOBAL', 'Global Toggle'), ('PERCENTAGE', 'Percentage Rollout'), ('USER_LIST', 'Specific Users'), ('PLAN_BASED', 'Plan Based'), ('ROLE_BASED', 'Role Based')], default='GLOBAL', max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of users to enable for (0-100)')),
                ('allowed_user_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs to enable for')),
                ('allowed_plans', models.JSONField(blank=True, default=list, help_text='List of plan slugs to enable for')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="List of roles to enable for (e.g., ['SUPER_ADMIN', 'ADMIN'])")),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='subscriptions.featureflag')),
            ],
            options={
                'db_table': 'feature_flag_audits',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('tax_id', models.CharField(help_text='VAT/GST/Tax Registration Number', max_length=50)),
                ('tax_id_type', models.CharField(help_text='e.g., EU VAT, GST, EIN', max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_exemptions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_exemptions',
                'unique_together': {('user', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this tax rule', max_length=100)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('region', models.CharField(blank=True, help_text='Optional: State/Province/Region code', max_length=100)),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax'), ('GST', 'Goods and Services Tax'), ('SALES_TAX', 'Sales Tax'), ('WITHHOLDING', 'Withholding Tax'), ('CUSTOM', 'Custom Tax')], default='VAT', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('is_inclusive', models.BooleanField(default=False, help_text='Whether tax is included in displayed prices')),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_digital', models.BooleanField(default=True, help_text='Whether this tax applies to digital services')),
                ('applies_to_business', models.BooleanField(default=True, help_text='Whether this tax applies to B2B transactions')),
                ('registration_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue threshold for tax registration requirement', max_digits=12, null=True)),
                ('threshold_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_rules',
                'ordering': ['country_code', 'region'],
                'unique_together': {('country_code', 'region', 'tax_type')},
            },
        ),
    ]
