# Generated by Django 5.2.9 on 2025-12-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_phase1_rbac_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_usage_records', to='subscriptions.feature')),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'feature', 'date'], name='subscriptio_ip_addr_32e0d3_idx')],
                'unique_together': {('ip_address', 'feature', 'date')},
            },
        ),
    ]
