# Generated by Django 5.2.9 on 2025-12-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_guestfeatureusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfiguration',
            name='default_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='regionalpricing',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='threshold_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
