# Generated by Django 5.2.9 on 2025-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twofactorbackupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='User is banned until this date', null=True),
        ),
    ]
