# Generated by Django 5.2.9 on 2025-12-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apikey'),
        ('subscriptions', '0008_taxconfiguration_coupon_couponusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='invalid_credentials', max_length=100)),
            ],
            options={
                'db_table': 'failed_login_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_length', models.PositiveIntegerField(default=8)),
                ('max_length', models.PositiveIntegerField(default=128)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_special', models.BooleanField(default=True)),
                ('special_characters', models.CharField(default='!@#$%^&*()_+-=[]{}|;\':",./<>?', max_length=100)),
                ('prevent_reuse_count', models.PositiveIntegerField(default=5, help_text='Number of previous passwords to check')),
                ('password_expires_days', models.PositiveIntegerField(default=0, help_text='0 = never expires')),
                ('warn_before_expiry_days', models.PositiveIntegerField(default=7)),
                ('max_failed_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=30)),
                ('check_breached_passwords', models.BooleanField(default=True, help_text='Check against known breached passwords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'password_policies',
            },
        ),
        migrations.CreateModel(
            name='IPRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Single IP address')),
                ('ip_range_start', models.GenericIPAddressField(blank=True, help_text='IP range start (optional)', null=True)),
                ('ip_range_end', models.GenericIPAddressField(blank=True, help_text='IP range end (optional)', null=True)),
                ('cidr', models.CharField(blank=True, help_text='CIDR notation e.g. 192.168.1.0/24', max_length=50, null=True)),
                ('rule_type', models.CharField(choices=[('WHITELIST', 'Whitelist'), ('BLACKLIST', 'Blacklist')], max_length=20)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global - All endpoints'), ('ADMIN', 'Admin Panel Only'), ('API', 'API Only'), ('AUTH', 'Authentication Only')], default='GLOBAL', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why this rule was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hits', models.PositiveIntegerField(default=0, help_text='Number of times this rule was triggered')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ip_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global - All users'), ('ROLE', 'Per Role'), ('PLAN', 'Per Plan'), ('USER', 'Specific User'), ('ENDPOINT', 'Specific Endpoint')], default='GLOBAL', max_length=20)),
                ('target_role', models.CharField(blank=True, help_text='USER, ADMIN, SUPER_ADMIN', max_length=20, null=True)),
                ('target_endpoint', models.CharField(blank=True, help_text='API endpoint pattern', max_length=200, null=True)),
                ('requests_allowed', models.PositiveIntegerField(default=100)),
                ('time_window', models.CharField(choices=[('SECOND', 'Per Second'), ('MINUTE', 'Per Minute'), ('HOUR', 'Per Hour'), ('DAY', 'Per Day')], default='MINUTE', max_length=20)),
                ('burst_allowed', models.PositiveIntegerField(default=20, help_text='Extra requests allowed in burst')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate_limit_rules',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('category', models.CharField(choices=[('SECURITY', 'Security'), ('PROCESSING', 'Processing'), ('STORAGE', 'Storage'), ('PAYMENT', 'Payment'), ('EMAIL', 'Email'), ('FEATURE', 'Feature'), ('LIMITS', 'Limits'), ('DISPLAY', 'Display')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(default='STRING', max_length=20)),
                ('min_value', models.CharField(blank=True, max_length=50, null=True)),
                ('max_value', models.CharField(blank=True, max_length=50, null=True)),
                ('allowed_values', models.JSONField(blank=True, help_text='List of allowed values', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_configurations',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('ADMIN_ACTION', 'Admin Action'), ('SYSTEM', 'System')], max_length=20)),
                ('resource_type', models.CharField(help_text='Model name or resource type', max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, help_text='Previous state', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['action_type', 'created_at'], name='audit_logs_action__94af82_idx')],
            },
        ),
    ]
