# Generated by Django 5.2.9 on 2025-12-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_failedloginattempt_passwordpolicy_iprule_and_more'),
        ('teams', '0002_teaminvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('provider_type', models.CharField(choices=[('SAML', 'SAML 2.0'), ('OIDC', 'OpenID Connect'), ('LDAP', 'LDAP/Active Directory'), ('AZURE_AD', 'Azure Active Directory'), ('OKTA', 'Okta'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('ONELOGIN', 'OneLogin')], max_length=20)),
                ('entity_id', models.CharField(blank=True, help_text='IdP Entity ID', max_length=500)),
                ('sso_url', models.URLField(blank=True, help_text='IdP SSO URL')),
                ('slo_url', models.URLField(blank=True, help_text='IdP Single Logout URL')),
                ('certificate', models.TextField(blank=True, help_text='IdP X.509 Certificate')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('authorization_endpoint', models.URLField(blank=True)),
                ('token_endpoint', models.URLField(blank=True)),
                ('userinfo_endpoint', models.URLField(blank=True)),
                ('jwks_uri', models.URLField(blank=True)),
                ('ldap_server', models.CharField(blank=True, max_length=255)),
                ('ldap_port', models.PositiveIntegerField(default=389)),
                ('ldap_use_ssl', models.BooleanField(default=False)),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255)),
                ('ldap_bind_password', models.CharField(blank=True, max_length=255)),
                ('ldap_base_dn', models.CharField(blank=True, max_length=255)),
                ('ldap_user_filter', models.CharField(default='(uid={username})', max_length=255)),
                ('attribute_mapping', models.JSONField(blank=True, default=dict, help_text='Map IdP attributes to user fields')),
                ('auto_create_users', models.BooleanField(default=True, help_text='Auto-create users on first SSO login')),
                ('default_role', models.CharField(default='USER', max_length=20)),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Restrict to specific email domains')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TESTING', 'Testing')], default='INACTIVE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default SSO for organization')),
                ('metadata_url', models.URLField(blank=True, help_text='IdP Metadata URL for auto-configuration')),
                ('sp_entity_id', models.CharField(blank=True, help_text='Service Provider Entity ID', max_length=500)),
                ('sp_acs_url', models.URLField(blank=True, help_text='Service Provider ACS URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='teams.team')),
            ],
            options={
                'verbose_name': 'SSO Provider',
                'verbose_name_plural': 'SSO Providers',
                'db_table': 'sso_providers',
            },
        ),
        migrations.CreateModel(
            name='SSOLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('relay_state', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ssoprovider')),
            ],
            options={
                'db_table': 'sso_login_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_index', models.CharField(blank=True, help_text='IdP session index for SLO', max_length=255)),
                ('name_id', models.CharField(blank=True, help_text='SAML NameID', max_length=255)),
                ('idp_attributes', models.JSONField(blank=True, default=dict, help_text='Raw attributes from IdP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ssoprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sso_sessions',
            },
        ),
    ]
