# Generated by Django 5.2.9 on 2025-12-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ssoprovider_ssologinattempt_ssosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssoprovider',
            name='team',
        ),
        migrations.RemoveField(
            model_name='ssosession',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ssosession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorbackupcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='banned_until',
        ),
        migrations.DeleteModel(
            name='SSOLoginAttempt',
        ),
        migrations.DeleteModel(
            name='SSOProvider',
        ),
        migrations.DeleteModel(
            name='SSOSession',
        ),
        migrations.DeleteModel(
            name='TwoFactorBackupCode',
        ),
    ]
