# Generated by Django 5.2.9 on 2025-12-16 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_ban_reason_user_banned_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Searchable action key, e.g. 'delete_user', 'update_plan'", max_length=255)),
                ('target_model', models.CharField(help_text='Model name of the target object', max_length=100)),
                ('target_object_id', models.CharField(help_text='ID of the target object', max_length=100)),
                ('target_repr', models.CharField(help_text='String representation of target object for readability', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Changeset or additional context')),
                ('status', models.CharField(default='SUCCESS', help_text='SUCCESS/FAILURE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action'], name='system_acti_actor_i_f3e67c_idx'), models.Index(fields=['target_model', 'target_object_id'], name='system_acti_target__1d29b6_idx'), models.Index(fields=['created_at'], name='system_acti_created_a46910_idx')],
            },
        ),
    ]
