# Generated by Django 5.2.9 on 2025-12-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='flagged_by',
            field=models.ForeignKey(blank=True, help_text='Admin who flagged this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='flagged_reason',
            field=models.TextField(blank=True, help_text='Reason for flagging'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Whether account is flagged for review'),
        ),
    ]
