# Generated by Django 5.2.9 on 2025-12-15 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(db_index=True, max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('queue_name', models.CharField(default='default', max_length=50)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='files.fileasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs_job',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_joblog',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='jobs_job_status_b9fcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='jobs_job_user_id_58dc09_idx'),
        ),
    ]
