# Generated by Django 5.2.9 on 2025-12-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_cloudconnection_unique_together_and_more'),
        ('jobs', '0002_alter_job_file_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='files.fileasset'),
        ),
    ]
