# Generated by Django 5.2.9 on 2025-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_file_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='batch_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='is_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='operation',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
