# Generated by Django 5.2.9 on 2025-12-17 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_batch_id_job_batch_index_job_is_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(help_text='Tool operation being performed', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Shared parameters for all jobs')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=25)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('completed_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('output_files', models.JSONField(blank=True, default=list, help_text='List of output file UUIDs')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error messages per file')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
