import {
    Merge,
    Split,
    Minimize2,
    FileText,
    FileImage,
    Image,
    RotateCw,
    Lock,
    Unlock,
    Stamp,
    Type,
    ArrowRightLeft,
    FileSpreadsheet,
    Presentation,
    Shield,
    Trash2,
    Move,
    Crop,
    ScanLine,
    Search,
    GitCompare,
    Eraser,
    Workflow,
    Globe,
    Wrench,
} from "lucide-react";

export const tools = [
    {
        title: "Merge PDF",
        description: "Combine PDFs in the order you want with the easiest PDF merger available.",
        icon: Merge,
        href: "/merge-pdf",
        category: "Organize PDF",
    },
    {
        title: "Split PDF",
        description: "Separate one page or a whole set for easy conversion into independent PDF files.",
        icon: Split,
        href: "/split-pdf",
        category: "Organize PDF",
    },
    {
        title: "Compress PDF",
        description: "Reduce file size while optimizing for maximal PDF quality.",
        icon: Minimize2,
        href: "/compress-pdf",
        category: "Optimize PDF",
    },
    {
        title: "PDF to Word",
        description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
        icon: FileText,
        href: "/pdf-to-word",
        category: "Convert PDF",
    },
    {
        title: "PDF to PowerPoint",
        description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
        icon: Presentation,
        href: "/pdf-to-powerpoint",
        category: "Convert PDF",
    },
    {
        title: "PDF to Excel",
        description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
        icon: FileSpreadsheet,
        href: "/pdf-to-excel",
        category: "Convert PDF",
    },
    {
        title: "Word to PDF",
        description: "Make DOC and DOCX files easy to read by converting them to PDF.",
        icon: FileText,
        href: "/word-to-pdf",
        category: "Convert to PDF",
    },
    {
        title: "PowerPoint to PDF",
        description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
        icon: Presentation,
        href: "/powerpoint-to-pdf",
        category: "Convert to PDF",
    },
    {
        title: "Excel to PDF",
        description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
        icon: FileSpreadsheet,
        href: "/excel-to-pdf",
        category: "Convert to PDF",
    },
    {
        title: "Edit PDF",
        description: "Add text, images, shapes or freehand annotations to a PDF document.",
        icon: Type,
        href: "/edit-pdf",
        category: "Edit PDF",
        isNew: true,
    },
    {
        title: "PDF to JPG",
        description: "Convert each PDF page into a JPG or extract all images contained in a PDF.",
        icon: Image,
        href: "/pdf-to-jpg",
        category: "Convert from PDF",
    },
    {
        title: "JPG to PDF",
        description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
        icon: FileImage,
        href: "/jpg-to-pdf",
        category: "Convert to PDF",
    },
    {
        title: "Sign PDF",
        description: "Sign yourself or request electronic signatures from others.",
        icon: FileText,
        href: "/sign-pdf",
        category: "PDF Security",
    },
    {
        title: "Watermark",
        description: "Stamp an image or text over your PDF in seconds.",
        icon: Stamp,
        href: "/watermark-pdf",
        category: "Edit PDF",
    },
    {
        title: "Rotate PDF",
        description: "Rotate your PDFs the way you need them.",
        icon: RotateCw,
        href: "/rotate-pdf",
        category: "Edit PDF",
    },
    {
        title: "Unlock PDF",
        description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
        icon: Unlock,
        href: "/unlock-pdf",
        category: "PDF Security",
    },
    {
        title: "Protect PDF",
        description: "Protect PDF files with a password. Encrypt PDF documents.",
        icon: Lock,
        href: "/protect-pdf",
        category: "PDF Security",
    },
    {
        title: "Organize PDF",
        description: "Sort pages of your PDF file however you like. Delete or add PDF pages.",
        icon: Move,
        href: "/organize-pdf",
        category: "Organize PDF",
    },
    {
        title: "PDF to PDF/A",
        description: "Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving.",
        icon: Shield,
        href: "/pdf-to-pdfa",
        category: "Convert PDF",
    },
    {
        title: "Repair PDF",
        description: "Repair a damaged PDF and recover data from corrupt PDF.",
        icon: Wrench,
        href: "/repair-pdf",
        category: "Optimize PDF",
    },
    {
        title: "Page Numbers",
        description: "Add page numbers into PDFs with ease.",
        icon: Type,
        href: "/page-numbers",
        category: "Edit PDF",
    },
    {
        title: "Scan to PDF",
        description: "Capture document scans from your mobile device and send them instantly to your browser.",
        icon: ScanLine,
        href: "/scan-to-pdf",
        category: "Organize PDF",
    },
    {
        title: "OCR PDF",
        description: "Easily convert scanned PDF into searchable and selectable documents.",
        icon: Search,
        href: "/ocr-pdf",
        category: "Optimize PDF",
    },
    {
        title: "Compare PDF",
        description: "Show a side-by-side document comparison and easily spot changes.",
        icon: GitCompare,
        href: "/compare-pdf",
        category: "Edit PDF",
        isNew: true,
    },
    {
        title: "Redact PDF",
        description: "Redact text and graphics to permanently remove sensitive information.",
        icon: Eraser,
        href: "/redact-pdf",
        category: "PDF Security",
        isNew: true,
    },
    {
        title: "Crop PDF",
        description: "Crop margins of PDF documents or select specific areas.",
        icon: Crop,
        href: "/crop-pdf",
        category: "Edit PDF",
        isNew: true,
    },
    {
        title: "HTML to PDF",
        description: "Convert webpages in HTML to PDF.",
        icon: Globe,
        href: "/html-to-pdf",
        category: "Convert to PDF",
    },
    {
        title: "Create Workflow",
        description: "Create custom workflows with your favorite tools, automate tasks, and reuse them anytime.",
        icon: Workflow,
        href: "/create-workflow",
        category: "Workflows",
    },
];
