# Generated by Django 5.2.9 on 2025-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbranding',
            name='platform_name',
            field=models.CharField(default='18+ PDF', max_length=100),
        ),
    ]
