# Generated by Django 5.2.9 on 2025-12-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_contentcategory_faqarticle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementdismissal',
            name='announcement',
        ),
        migrations.AlterUniqueTogether(
            name='announcementdismissal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementdismissal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='faqarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faqarticle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='faqarticle',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='related_invoice',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='related_job',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementDismissal',
        ),
        migrations.DeleteModel(
            name='ContentCategory',
        ),
        migrations.DeleteModel(
            name='FAQArticle',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
