# Generated by Django 5.2.9 on 2025-12-31 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_announcement_contentcategory_faqarticle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person providing feedback', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person providing feedback', max_length=254)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug'), ('functionality', 'Add functionality'), ('ui', 'Change UI')], help_text='Type of feedback', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when feedback was submitted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this feedback has been addressed')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the feedback was resolved', null=True)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes from admin/staff')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the feedback (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'core_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_feedba_created_e27107_idx'), models.Index(fields=['feedback_type'], name='core_feedba_feedbac_e768a0_idx'), models.Index(fields=['is_resolved'], name='core_feedba_is_reso_35d0c6_idx')],
            },
        ),
    ]
