# Generated by Django 5.2.9 on 2025-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='proof_link',
            field=models.URLField(blank=True, help_text='Optional link to cloud drive attachment (Google Drive, Dropbox, etc.)', max_length=500, null=True),
        ),
    ]
