import {
    FaObjectGroup,
    FaColumns,
    FaCompressArrowsAlt,
    FaFileWord,
    FaFilePowerpoint,
    FaFileExcel,
    FaEdit,

    FaFileImage,
    FaFileSignature,
    FaStamp,
    FaSyncAlt,
    FaUnlock,
    FaLock,
    FaSort,
    FaFilePdf,
    FaBandAid,
    FaListOl,
    FaPrint,
    FaEye,
    FaNotEqual,
    FaUserSecret,
    FaCrop,
    FaCode,
    FaCogs,
    FaEraser,
} from "react-icons/fa";

// Professional color palette for different tool types
export const toolColors = {
    pdf: "#E42527",        // PDF Red
    word: "#2B579A",       // Word Blue
    excel: "#217346",      // Excel Green
    powerpoint: "#D24726", // PowerPoint Orange
    image: "#7B5CD6",      // Image Purple
    security: "#0F766E",   // Security Teal
    organize: "#0369A1",   // Organize Sky Blue
    edit: "#7C3AED",       // Edit Violet
    optimize: "#EA580C",   // Optimize Orange
    workflow: "#DB2777",   // Workflow Pink
    convert: "#059669",    // Convert Emerald
};

export const tools = [
    {
        title: "Merge PDF",
        description: "Combine PDFs in the order you want with the easiest PDF merger available.",
        icon: "/home/merge.png",
        href: "/merge-pdf",
        category: "Organize PDF",
        color: toolColors.pdf,
        userCount: 12847,
    },
    {
        title: "Split PDF",
        description: "Separate one page or a whole set for easy conversion into independent PDF files.",
        icon: "/home/split-pdf.png",
        href: "/split-pdf",
        category: "Organize PDF",
        color: toolColors.pdf,
        userCount: 9563,
    },
    {
        title: "Compress PDF",
        description: "Reduce file size while optimizing for maximal PDF quality.",
        icon: "/home/compress-pdf.png",
        href: "/compress-pdf",
        category: "Optimize PDF",
        color: toolColors.optimize,
        userCount: 15234,
    },
    {
        title: "PDF to Word",
        description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
        icon: "/home/pdf-word.png",
        href: "/pdf-to-word",
        category: "Convert PDF",
        color: toolColors.word,
        userCount: 18956,
    },
    {
        title: "PDF to PowerPoint",
        description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
        icon: "/home/pdf-pptx.png",
        href: "/pdf-to-powerpoint",
        category: "Convert PDF",
        color: toolColors.powerpoint,
        userCount: 7842,
    },
    {
        title: "PDF to Excel",
        description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
        icon: "/home/pdf-excel.png",
        href: "/pdf-to-excel",
        category: "Convert PDF",
        color: toolColors.excel,
        userCount: 11289,
    },
    {
        title: "Word to PDF",
        description: "Make DOC and DOCX files easy to read by converting them to PDF.",
        icon: "/home/wrd-pdf.png",
        href: "/word-to-pdf",
        category: "Convert to PDF",
        color: toolColors.word,
    },
    {
        title: "PowerPoint to PDF",
        description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
        icon: "/home/pptx-pdf.png",
        href: "/powerpoint-to-pdf",
        category: "Convert to PDF",
        color: toolColors.powerpoint,
        userCount: 8391,
    },
    {
        title: "Excel to PDF",
        description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
        icon: "/home/excel-pdf.png",
        href: "/excel-to-pdf",
        category: "Convert to PDF",
        color: toolColors.excel,
        userCount: 9847,
    },
    {
        title: "Edit PDF",
        description: "Add text, images, shapes or freehand annotations to a PDF document.",
        icon: "/home/edit-pdf.png",
        href: "/edit-pdf",
        isNew: true,
        color: toolColors.edit,
        comingSoon: true,
        userCount: 5234,
    },

    {
        title: "PDF to JPG",
        description: "Convert each PDF page into a JPG or extract all images contained in a PDF.",
        icon: "/home/pdf-img.png",
        href: "/pdf-to-jpg",
        category: "Convert from PDF",
        color: toolColors.image,
        userCount: 13567,
    },
    {
        title: "JPG to PDF",
        description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
        icon: "/home/jpg-pdf.png",
        href: "/jpg-to-pdf",
        category: "Convert to PDF",
        color: toolColors.image,
        userCount: 16834,
    },
    {
        title: "Sign PDF",
        description: "Sign yourself or request electronic signatures from others.",
        icon: "/home/sign.png",
        href: "/sign-pdf",
        category: "PDF Security",
        color: toolColors.security,
        userCount: 10562,
    },
    {
        title: "Watermark",
        description: "Stamp an image or text over your PDF in seconds.",
        icon: "/home/watermark-pdf.png",
        href: "/watermark-pdf",
        category: "Edit PDF",
        color: toolColors.edit,
        userCount: 7293,
    },
    {
        title: "Rotate PDF",
        description: "Rotate your PDFs the way you need them.",
        icon: "/home/rotate-pdf.png",
        href: "/rotate-pdf",
        category: "Edit PDF",
        color: toolColors.pdf,
        userCount: 6481,
    },
    {
        title: "Unlock PDF",
        description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
        icon: "/home/unlock-pdf.png",
        href: "/unlock-pdf",
        category: "PDF Security",
        color: toolColors.security,
        userCount: 8926,
    },
    {
        title: "Protect PDF",
        description: "Protect PDF files with a password. Encrypt PDF documents.",
        icon: "/home/protect-pdf.png",
        href: "/protect-pdf",
        category: "PDF Security",
        color: toolColors.security,
        userCount: 11473,
    },
    {
        title: "Organize PDF",
        description: "Sort pages of your PDF file however you like. Delete or add PDF pages.",
        icon: "/home/organize-pdf.png",
        href: "/organize-pdf",
        category: "Organize PDF",
        color: toolColors.organize,
        userCount: 9128,
    },
    {
        title: "PDF to PDF/A",
        description: "Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving.",
        icon: "/home/pdf-pdf-a.png",
        href: "/pdf-to-pdfa",
        category: "Convert PDF",
        color: toolColors.pdf,
        userCount: 4567,
    },
    {
        title: "Page Numbers",
        description: "Add page numbers into PDFs with ease.",
        icon: "/home/page-number-pdf.png",
        href: "/page-numbers",
        category: "Edit PDF",
        color: toolColors.edit,
        userCount: 7854,
    },
    {
        title: "OCR PDF",
        description: "Easily convert scanned PDF into searchable and selectable documents.",
        icon: "/home/ocr.png",
        href: "/ocr-pdf",
        category: "Optimize PDF",
        color: toolColors.optimize,
        userCount: 12394,
    },
    {
        title: "Compare PDF",
        description: "Show a side-by-side document comparison and easily spot changes.",
        icon: "/home/compare-pdf.png",
        href: "/compare-pdf",
        category: "Edit PDF",
        isNew: true,
        color: toolColors.pdf,
        userCount: 3892,
    },
    {
        title: "Redact PDF",
        description: "Redact text and graphics to permanently remove sensitive information.",
        icon: "/home/redact.png",
        href: "/redact-pdf",
        category: "PDF Security",
        isNew: true,
        color: toolColors.security,
        userCount: 6745,
    },
    {
        title: "Crop PDF",
        description: "Crop margins of PDF documents or select specific areas.",
        icon: "/home/crop.png",
        href: "/crop-pdf",
        category: "Edit PDF",
        isNew: true,
        color: toolColors.edit,
        userCount: 5628,
    },
    {
        title: "HTML to PDF",
        description: "Convert webpages in HTML to PDF.",
        icon: "/home/html-pdf.png",
        href: "/html-to-pdf",
        category: "Convert to PDF",
        color: toolColors.convert,
        userCount: 8237,
    },
    {
        title: "Create Workflow",
        description: "Create custom workflows with your favorite tools, automate tasks, and reuse them anytime.",
        icon: "/home/workflow.png",
        href: "/create-workflow",
        category: "Workflows",
        color: toolColors.workflow,
        comingSoon: true,
        userCount: 2156,
    },
    {
        title: "Metadata Cleaner",
        description: "Remove hidden metadata and personal information from your PDF files.",
        icon: "/home/metadata.png",
        href: "/metadata-cleaner",
        category: "PDF Security",
        isNew: true,
        color: toolColors.security,
        userCount: 4983,
    },
    {
        title: "Extract Images",
        description: "Extract all images from a PDF document.",
        icon: "/home/extract-image.png",
        href: "/extract-images",
        category: "Convert from PDF",
        color: toolColors.image,
        userCount: 7196,
    },
    {
        title: "Scan to PDF",
        description: "Scan to PDF because your papers deserve a digital retirement plan.",
        icon: "/home/scan-pdf.png",
        href: "/scan-to-pdf",
        category: "Convert to PDF",
        isNew: true,
        color: toolColors.convert,
        userCount: 9471,
    },
    {
        title: "Repair PDF",
        description: "PDFs break too luckily, theirs is easier to fix.",
        icon: "/home/repair-pdf.png",
        href: "/repair-pdf",
        category: "Optimize PDF",
        color: toolColors.optimize,
        userCount: 5839,
    },
];
